[go to notebook](http://localhost:8888/notebooks/scripts/9.ipynb)

In [10]:
import pandas as pd
pd.set_option('display.max_rows', 5)

In [11]:
movies = pd.read_csv('../data/imdb_1000.csv')
movies

,star_rating,title,content_rating,genre,duration,actors_list
0,9.3,The Shawshank Redemption,R,Crime,142,"[u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt..."
1,9.2,The Godfather,R,Crime,175,"[u'Marlon Brando', u'Al Pacino', u'James Caan']"
...,...,...,...,...,...,...
977,7.4,Poltergeist,PG,Horror,114,"[u'JoBeth Williams', u""Heather O'Rourke"", u'Cr..."
978,7.4,Wall Street,R,Crime,126,"[u'Charlie Sheen', u'Michael Douglas', u'Tamar..."

In [12]:
# select intersection (don't forget bracket)
print movies[(movies.duration >=200) & (movies.genre == 'Drama')]

# select union
movies[(movies.duration >=200) | (movies.genre == 'Drama')]

     star_rating               title content_rating  genre  duration  \
17           8.7       Seven Samurai        UNRATED  Drama       207
157          8.2  Gone with the Wind              G  Drama       238
476          7.8              Hamlet          PG-13  Drama       242

                                           actors_list
17   [u'Toshir\xf4 Mifune', u'Takashi Shimura', u'K...
157  [u'Clark Gable', u'Vivien Leigh', u'Thomas Mit...
476  [u'Kenneth Branagh', u'Julie Christie', u'Dere...

,star_rating,title,content_rating,genre,duration,actors_list
2,9.1,The Godfather: Part II,R,Crime,200,"[u'Al Pacino', u'Robert De Niro', u'Robert Duv..."
5,8.9,12 Angry Men,NOT RATED,Drama,96,"[u'Henry Fonda', u'Lee J. Cobb', u'Martin Bals..."
...,...,...,...,...,...,...
972,7.4,Blue Valentine,NC-17,Drama,112,"[u'Ryan Gosling', u'Michelle Williams', u'John..."
973,7.4,The Cider House Rules,PG-13,Drama,126,"[u'Tobey Maguire', u'Charlize Theron', u'Micha..."

In [13]:
# display: pretty print
from IPython.display import display
display(movies[(movies.genre == 'Crime') | (movies.genre == 'Drama') | (movies.genre == 'Action')])

# isin: contain the latter or not 
movies[movies.genre.isin(['Crime', 'Drama'])]

,star_rating,title,content_rating,genre,duration,actors_list
0,9.3,The Shawshank Redemption,R,Crime,142,"[u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt..."
1,9.2,The Godfather,R,Crime,175,"[u'Marlon Brando', u'Al Pacino', u'James Caan']"
...,...,...,...,...,...,...
976,7.4,Master and Commander: The Far Side of the World,PG-13,Action,138,"[u'Russell Crowe', u'Paul Bettany', u'Billy Bo..."
978,7.4,Wall Street,R,Crime,126,"[u'Charlie Sheen', u'Michael Douglas', u'Tamar..."

,star_rating,title,content_rating,genre,duration,actors_list
0,9.3,The Shawshank Redemption,R,Crime,142,"[u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt..."
1,9.2,The Godfather,R,Crime,175,"[u'Marlon Brando', u'Al Pacino', u'James Caan']"
...,...,...,...,...,...,...
973,7.4,The Cider House Rules,PG-13,Drama,126,"[u'Tobey Maguire', u'Charlize Theron', u'Micha..."
978,7.4,Wall Street,R,Crime,126,"[u'Charlie Sheen', u'Michael Douglas', u'Tamar..."